
/* Drop Tables */

DROP TABLE CALENDAR CASCADE CONSTRAINTS;
DROP TABLE CHATBOT CASCADE CONSTRAINTS;
DROP TABLE MESSAGE_READ CASCADE CONSTRAINTS;
DROP TABLE CHATTING_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE JOIN_CHATTING CASCADE CONSTRAINTS;
DROP TABLE CHATTING_ROOM CASCADE CONSTRAINTS;
DROP TABLE COORDINATES CASCADE CONSTRAINTS;
DROP TABLE CS_BOARD CASCADE CONSTRAINTS;
DROP TABLE INTER_CITY CASCADE CONSTRAINTS;
DROP TABLE JWT CASCADE CONSTRAINTS;
DROP TABLE LIKEY CASCADE CONSTRAINTS;
DROP TABLE RECEIVE_PAYMENT CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_EVALUATION CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE TRIP_DAYS CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_BORAD CASCADE CONSTRAINTS;
DROP TABLE SOCIAL_USER CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;




/* Create Tables */

-- 여행 날짜 등록
CREATE TABLE CALENDAR
(
	-- 캘린더 고유 번호
	ID long NOT NULL,
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- STARTDATE
	STARTDATE date,
	-- ENDDATE
	ENDDATE date,
	PRIMARY KEY (ID)
);


-- 챗봇
CREATE TABLE CHATBOT
(
	-- 챗봇 고유 번호
	ID long NOT NULL,
	-- 질문DB
	INQUERY clob,
	-- 답변 로그
	ANSWER clob,
	PRIMARY KEY (ID)
);


-- 채팅 메시지
CREATE TABLE CHATTING_MESSAGE
(
	-- 채팅 메시지 고유번호
	ID long NOT NULL,
	-- 채팅방 고유번호
	ID long NOT NULL,
	-- 유저 고유번호
	USER_ID long NOT NULL,
	-- 메시지 내용
	CONTENT nvarchar2(100) NOT NULL,
	-- 생성 날짜
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	-- 생성 여부 : 1이 TRUE
	-- 0이 FALSE
	ISACTIVE char(1) DEFAULT '1' NOT NULL,
	-- 삭제날짜
	DELETED_AT timestamp,
	-- 삭제 여부 : 1이 TRUE
	-- 0이 FALSE
	ISDELETE char(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID)
);


-- 채팅방
CREATE TABLE CHATTING_ROOM
(
	-- 채팅방 고유번호
	ID long NOT NULL,
	-- 생성 날짜
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	-- 활성화 여부 : 1이 TRUE
	-- 0이 FALSE
	ISACTIVE char(1) DEFAULT '1' NOT NULL,
	-- 삭제 날짜
	DELETED_AT timestamp,
	-- 삭제 여부 : 1이 TRUE
	-- 0이 FALSE
	ISDELETE char(1) DEFAULT '0' NOT NULL,
	-- 수정 날짜
	UPDATED_AT timestamp,
	-- 수정 여부 : 1이 TRUE
	-- 0이 FALSE
	ISUPDATE char(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID)
);


-- 좌표
CREATE TABLE COORDINATES
(
	-- 좌표 고유번호
	ID long NOT NULL,
	-- 날짜 고유번호
	ID long NOT NULL,
	-- 좌표 순서 : 좌표 순서
	COORDINATE_ORDER number NOT NULL,
	-- 좌표 : 예시)
	-- '26.2021-148.2425'
	-- 국내 여행에 한해서 문자열 16자 고정
	COORDINATE varchar2(16) NOT NULL,
	-- 좌표 내용 : 길이는 몰루?
	CONTENT nvarchar2(200) NOT NULL,
	-- 생성 여부 : 1은 TRUE
	-- 0은 FALSE
	ISCREATE char(1) DEFAULT '1' NOT NULL,
	-- 생성 날짜
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	-- 삭제 여부 : 1은 TRUE
	-- 0은 FALSE
	ISDELETE char(1) DEFAULT '0' NOT NULL,
	-- 삭제 날짜
	DELETED_AT timestamp,
	PRIMARY KEY (ID)
);


-- 고객센터
CREATE TABLE CS_BOARD
(
	-- 고객센터 고유 번호
	ID long NOT NULL,
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 제목
	TITLE nvarchar2(50) NOT NULL,
	-- 질문 내용
	CONTENT clob NOT NULL,
	-- 답변내용
	COMMENT clob,
	-- 게시날짜
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	-- 활성화도 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	-- 
	-- 
	ISACTIVE char(1) DEFAULT '1' NOT NULL,
	-- 수정 날짜
	UPDATED_AT timestamp,
	-- 수정 유무 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISUPDATE char(1),
	-- 삭제 날짜
	DELETED_AT timestamp,
	-- 삭제 유무 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISDELETE char(1),
	PRIMARY KEY (ID)
);


-- 선호 도시
CREATE TABLE INTER_CITY
(
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 도시
	CITY nvarchar2(20) NOT NULL,
	PRIMARY KEY (ID, CITY),
	UNIQUE (ID, CITY)
);


-- 채팅방 입장
CREATE TABLE JOIN_CHATTING
(
	-- 채팅방 고유번호
	ID long NOT NULL,
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	PRIMARY KEY (ID, ID)
);


-- 토큰 관리
CREATE TABLE JWT
(
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 엑세스 토큰
	accessToken ,
	-- 리프레시 토큰
	refreshToken ,
	PRIMARY KEY (ID)
);


-- 상품 찜
CREATE TABLE LIKEY
(
	-- 가이드 상품 고유 번호
	ID long NOT NULL,
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	PRIMARY KEY (ID, ID)
);


-- 회원테이블
CREATE TABLE MEMBERS
(
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 이메일
	E_MAIL varchar2(50) NOT NULL UNIQUE,
	-- 이름
	NAME nvarchar2(10) NOT NULL,
	-- 비밀번호
	PASSWORD varchar2(20) NOT NULL,
	-- 성별
	GENDER nvarchar2(5),
	-- BIRTHDAY
	BIRTHDAY date,
	-- 전화
	TELNUMBER nvarchar2(18),
	-- 주소
	ADDRESS nvarchar2(50),
	-- 생성일
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	-- 활성화 여부 : 1이 true
	-- 0이 false
	ISACTIVE char(1) DEFAULT '1' NOT NULL,
	-- 수정 시간
	UPDATED_AT timestamp,
	-- 수정 여부 : 1이 TRUE
	-- 0이 FALSE
	ISUPDATE char(1) DEFAULT '0' NOT NULL,
	-- 삭제날짜
	DELETED_AT timestamp,
	-- 삭제 여부 : 1이 TRUE
	-- 0이 FALSE
	ISDELETE char(1) DEFAULT '0' NOT NULL,
	-- 소셜 연동 여부 : 1이면 TRUE
	-- 0이면 FALSE
	ISSOCIAL char(1) NOT NULL,
	-- 소셜 연동 날짜
	SOCIAL_AT timestamp,
	-- 가이드, 관리자
	ROLE nvarchar2(10) NOT NULL,
	-- 가이드 자격증 : 사진으로 받죠
	GUIDELICENSE nvarchar2(100),
	PRIMARY KEY (ID)
);


-- 읽음 표시
CREATE TABLE MESSAGE_READ
(
	-- 채팅 메시지 고유번호
	ID long NOT NULL,
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 읽음 여부 : 1이 TRUE
	-- 0이 FALSE
	ISREAD char(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID, ID)
);


-- 결제
CREATE TABLE PAYMENT
(
	-- 토스에서 받은 결제 고유 번호
	ID long NOT NULL,
	-- 가이드 상품 고유 번호
	ID long NOT NULL,
	-- 결제 금액
	PRICE number DEFAULT 1000 NOT NULL,
	-- 결제 수단
	PAY_METHOD nvarchar2(20) NOT NULL,
	-- 결제 시간
	CREATED_AT timestamp NOT NULL,
	-- 결제 성공 유무 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISACTIVE char(1) DEFAULT '1' NOT NULL,
	PRIMARY KEY (ID)
);


-- 가이드 상품 게시판
CREATE TABLE PRODUCT_BORAD
(
	-- 가이드 상품 고유 번호
	ID long NOT NULL,
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 제목
	TITLE nvarchar2(20) NOT NULL,
	-- 내용
	CONTENT nclob,
	-- 생성날짜
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	-- 활성화 정도 : 1이면 TRUE
	-- 0이면 FALSE
	-- 
	-- 
	-- 
	ISACTIVE char(1),
	-- AI평가 유무 : 1이면 TRUE
	-- 0이면 FALSE
	-- 
	ISEVALUEATION char(1) DEFAULT '0' NOT NULL,
	-- 여행 도시 : ,로 나열
	-- 색인, 검색용으로 사용예정
	-- 
	CITY nvarchar2(30) NOT NULL,
	-- 수정날짜
	UPDATED_AT timestamp,
	-- 수정여부 : 1이면 TRUE
	-- 0이면 TRUE
	-- 
	ISUPDATE char(1),
	PRIMARY KEY (ID)
);


-- AI평가
CREATE TABLE PRODUCT_EVALUATION
(
	-- AI평가 고유 번호
	ID long NOT NULL,
	-- 가이드 상품 고유 번호
	ID long NOT NULL,
	-- 평가 날짜
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	-- 점수
	SCORE number,
	-- 점수에 대한 내용
	CONTENT clob,
	PRIMARY KEY (ID)
);


-- 결제 영수증
CREATE TABLE RECEIVE_PAYMENT
(
	-- 토스에서 받은 결제 고유 번호
	ID long NOT NULL,
	-- 토스에서 받은 결제 고유 번호
	ID long NOT NULL,
	-- 결제 금액
	PRICE number,
	-- 결제 수단
	PAY_METHOD nvarchar2(20),
	-- 결제 시간
	CREATED_AT timestamp,
	-- 결제 성공 유무 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISACTIVE char(1) DEFAULT '1',
	PRIMARY KEY (ID)
);


-- 신고
CREATE TABLE REPORT
(
	-- 상품 고유 번호/신고 대상자
	ID long NOT NULL,
	-- 회원 고유 번호/신고자 : 회원 고유 ID
	ID long NOT NULL,
	-- 기타
	ETC nvarchar2(20),
	-- 리뷰 날짜
	CREATED_AT timestamp,
	-- 활성화도 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISACTIVE char(1),
	-- 평가항목 LIST : 회사 내규에 따름
	-- 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	LIST1 char(1) DEFAULT '0' NOT NULL,
	-- 평가항목 2 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	LIST2 char(1) DEFAULT '0' NOT NULL,
	-- 리스트 3 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	LIST3 char(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID, ID)
);


-- 리뷰
CREATE TABLE REVIEW
(
	-- 상품 고유 번호/신고 대상자
	ID long NOT NULL,
	-- 회원 고유 번호/신고자 : 회원 고유 ID
	ID long NOT NULL,
	-- 가이드 상품 고유 번호
	ID long NOT NULL,
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 평가항목 LIST : 회사 내규에 따름
	-- 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	LIST1 char(1) DEFAULT '0' NOT NULL,
	-- 평가항목 2 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	LIST2 char(1) DEFAULT '0' NOT NULL,
	-- 리스트 3 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	LIST3 char(1) DEFAULT '0' NOT NULL,
	-- 기타
	ETC nvarchar2(20),
	-- 리뷰 날짜
	CREATED_AT timestamp,
	-- 활성화도 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISACTIVE char(1) DEFAULT '1' NOT NULL,
	-- 수정 날짜
	UPDATED_AT timestamp,
	-- 수정 유무 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISUPDATE char(1) DEFAULT '0' NOT NULL,
	-- 삭제 날짜
	DELETED_AT timestamp,
	-- 삭제 유무 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	ISDELETE char(1) DEFAULT '0' NOT NULL,
	PRIMARY KEY (ID, ID)
);


-- 소셜 유저 테이블
CREATE TABLE SOCIAL_USER
(
	-- 회원 고유 번호 : 회원 고유 ID
	ID long NOT NULL,
	-- 카카오 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	KAKAO char(1) DEFAULT '0',
	-- 네이버 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	NAVER char(1) DEFAULT '0',
	-- 구글 : 1 - TRUE
	-- 0- FALSE
	-- 
	-- 
	GOOGLE char(1) DEFAULT '0',
	PRIMARY KEY (ID)
);


-- 여행 일수
CREATE TABLE TRIP_DAYS
(
	-- 날짜 고유번호
	ID long NOT NULL,
	-- 가이드 상품 고유 번호
	ID long NOT NULL,
	-- 날짜 : 몇번째 날인지
	DAY number NOT NULL,
	-- 수정 여부 : 1은 TRUE
	-- 0은 FALSE
	ISUPDATE char(1) DEFAULT '0' NOT NULL,
	-- 수정 날짜
	UPDATED_AT timestamp,
	-- 생성 여부
	ISCREATE char(1) DEFAULT '1' NOT NULL,
	-- 생성 날짜
	CREATED_AT timestamp DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (ID)
);



/* Comments */

COMMENT ON TABLE CALENDAR IS '여행 날짜 등록';
COMMENT ON COLUMN CALENDAR.ID IS '캘린더 고유 번호';
COMMENT ON COLUMN CALENDAR.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN CALENDAR.STARTDATE IS 'STARTDATE';
COMMENT ON COLUMN CALENDAR.ENDDATE IS 'ENDDATE';
COMMENT ON TABLE CHATBOT IS '챗봇';
COMMENT ON COLUMN CHATBOT.ID IS '챗봇 고유 번호';
COMMENT ON COLUMN CHATBOT.INQUERY IS '질문DB';
COMMENT ON COLUMN CHATBOT.ANSWER IS '답변 로그';
COMMENT ON TABLE CHATTING_MESSAGE IS '채팅 메시지';
COMMENT ON COLUMN CHATTING_MESSAGE.ID IS '채팅 메시지 고유번호';
COMMENT ON COLUMN CHATTING_MESSAGE.ID IS '채팅방 고유번호';
COMMENT ON COLUMN CHATTING_MESSAGE.USER_ID IS '유저 고유번호';
COMMENT ON COLUMN CHATTING_MESSAGE.CONTENT IS '메시지 내용';
COMMENT ON COLUMN CHATTING_MESSAGE.CREATED_AT IS '생성 날짜';
COMMENT ON COLUMN CHATTING_MESSAGE.ISACTIVE IS '생성 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON COLUMN CHATTING_MESSAGE.DELETED_AT IS '삭제날짜';
COMMENT ON COLUMN CHATTING_MESSAGE.ISDELETE IS '삭제 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON TABLE CHATTING_ROOM IS '채팅방';
COMMENT ON COLUMN CHATTING_ROOM.ID IS '채팅방 고유번호';
COMMENT ON COLUMN CHATTING_ROOM.CREATED_AT IS '생성 날짜';
COMMENT ON COLUMN CHATTING_ROOM.ISACTIVE IS '활성화 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON COLUMN CHATTING_ROOM.DELETED_AT IS '삭제 날짜';
COMMENT ON COLUMN CHATTING_ROOM.ISDELETE IS '삭제 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON COLUMN CHATTING_ROOM.UPDATED_AT IS '수정 날짜';
COMMENT ON COLUMN CHATTING_ROOM.ISUPDATE IS '수정 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON TABLE COORDINATES IS '좌표';
COMMENT ON COLUMN COORDINATES.ID IS '좌표 고유번호';
COMMENT ON COLUMN COORDINATES.ID IS '날짜 고유번호';
COMMENT ON COLUMN COORDINATES.COORDINATE_ORDER IS '좌표 순서 : 좌표 순서';
COMMENT ON COLUMN COORDINATES.COORDINATE IS '좌표 : 예시)
''26.2021-148.2425''
국내 여행에 한해서 문자열 16자 고정';
COMMENT ON COLUMN COORDINATES.CONTENT IS '좌표 내용 : 길이는 몰루?';
COMMENT ON COLUMN COORDINATES.ISCREATE IS '생성 여부 : 1은 TRUE
0은 FALSE';
COMMENT ON COLUMN COORDINATES.CREATED_AT IS '생성 날짜';
COMMENT ON COLUMN COORDINATES.ISDELETE IS '삭제 여부 : 1은 TRUE
0은 FALSE';
COMMENT ON COLUMN COORDINATES.DELETED_AT IS '삭제 날짜';
COMMENT ON TABLE CS_BOARD IS '고객센터';
COMMENT ON COLUMN CS_BOARD.ID IS '고객센터 고유 번호';
COMMENT ON COLUMN CS_BOARD.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN CS_BOARD.TITLE IS '제목';
COMMENT ON COLUMN CS_BOARD.CONTENT IS '질문 내용';
COMMENT ON COLUMN CS_BOARD.COMMENT IS '답변내용';
COMMENT ON COLUMN CS_BOARD.CREATED_AT IS '게시날짜';
COMMENT ON COLUMN CS_BOARD.ISACTIVE IS '활성화도 : 1 - TRUE
0- FALSE



';
COMMENT ON COLUMN CS_BOARD.UPDATED_AT IS '수정 날짜';
COMMENT ON COLUMN CS_BOARD.ISUPDATE IS '수정 유무 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN CS_BOARD.DELETED_AT IS '삭제 날짜';
COMMENT ON COLUMN CS_BOARD.ISDELETE IS '삭제 유무 : 1 - TRUE
0- FALSE

';
COMMENT ON TABLE INTER_CITY IS '선호 도시';
COMMENT ON COLUMN INTER_CITY.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN INTER_CITY.CITY IS '도시';
COMMENT ON TABLE JOIN_CHATTING IS '채팅방 입장';
COMMENT ON COLUMN JOIN_CHATTING.ID IS '채팅방 고유번호';
COMMENT ON COLUMN JOIN_CHATTING.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON TABLE JWT IS '토큰 관리';
COMMENT ON COLUMN JWT.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN JWT.accessToken IS '엑세스 토큰';
COMMENT ON COLUMN JWT.refreshToken IS '리프레시 토큰';
COMMENT ON TABLE LIKEY IS '상품 찜';
COMMENT ON COLUMN LIKEY.ID IS '가이드 상품 고유 번호';
COMMENT ON COLUMN LIKEY.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON TABLE MEMBERS IS '회원테이블';
COMMENT ON COLUMN MEMBERS.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN MEMBERS.E_MAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.NAME IS '이름';
COMMENT ON COLUMN MEMBERS.PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBERS.GENDER IS '성별';
COMMENT ON COLUMN MEMBERS.BIRTHDAY IS 'BIRTHDAY';
COMMENT ON COLUMN MEMBERS.TELNUMBER IS '전화';
COMMENT ON COLUMN MEMBERS.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBERS.CREATED_AT IS '생성일';
COMMENT ON COLUMN MEMBERS.ISACTIVE IS '활성화 여부 : 1이 true
0이 false';
COMMENT ON COLUMN MEMBERS.UPDATED_AT IS '수정 시간';
COMMENT ON COLUMN MEMBERS.ISUPDATE IS '수정 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON COLUMN MEMBERS.DELETED_AT IS '삭제날짜';
COMMENT ON COLUMN MEMBERS.ISDELETE IS '삭제 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON COLUMN MEMBERS.ISSOCIAL IS '소셜 연동 여부 : 1이면 TRUE
0이면 FALSE';
COMMENT ON COLUMN MEMBERS.SOCIAL_AT IS '소셜 연동 날짜';
COMMENT ON COLUMN MEMBERS.ROLE IS '가이드, 관리자';
COMMENT ON COLUMN MEMBERS.GUIDELICENSE IS '가이드 자격증 : 사진으로 받죠';
COMMENT ON TABLE MESSAGE_READ IS '읽음 표시';
COMMENT ON COLUMN MESSAGE_READ.ID IS '채팅 메시지 고유번호';
COMMENT ON COLUMN MESSAGE_READ.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN MESSAGE_READ.ISREAD IS '읽음 여부 : 1이 TRUE
0이 FALSE';
COMMENT ON TABLE PAYMENT IS '결제';
COMMENT ON COLUMN PAYMENT.ID IS '토스에서 받은 결제 고유 번호';
COMMENT ON COLUMN PAYMENT.ID IS '가이드 상품 고유 번호';
COMMENT ON COLUMN PAYMENT.PRICE IS '결제 금액';
COMMENT ON COLUMN PAYMENT.PAY_METHOD IS '결제 수단';
COMMENT ON COLUMN PAYMENT.CREATED_AT IS '결제 시간';
COMMENT ON COLUMN PAYMENT.ISACTIVE IS '결제 성공 유무 : 1 - TRUE
0- FALSE

';
COMMENT ON TABLE PRODUCT_BORAD IS '가이드 상품 게시판';
COMMENT ON COLUMN PRODUCT_BORAD.ID IS '가이드 상품 고유 번호';
COMMENT ON COLUMN PRODUCT_BORAD.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN PRODUCT_BORAD.TITLE IS '제목';
COMMENT ON COLUMN PRODUCT_BORAD.CONTENT IS '내용';
COMMENT ON COLUMN PRODUCT_BORAD.CREATED_AT IS '생성날짜';
COMMENT ON COLUMN PRODUCT_BORAD.ISACTIVE IS '활성화 정도 : 1이면 TRUE
0이면 FALSE


';
COMMENT ON COLUMN PRODUCT_BORAD.ISEVALUEATION IS 'AI평가 유무 : 1이면 TRUE
0이면 FALSE
';
COMMENT ON COLUMN PRODUCT_BORAD.CITY IS '여행 도시 : ,로 나열
색인, 검색용으로 사용예정
';
COMMENT ON COLUMN PRODUCT_BORAD.UPDATED_AT IS '수정날짜';
COMMENT ON COLUMN PRODUCT_BORAD.ISUPDATE IS '수정여부 : 1이면 TRUE
0이면 TRUE
';
COMMENT ON TABLE PRODUCT_EVALUATION IS 'AI평가';
COMMENT ON COLUMN PRODUCT_EVALUATION.ID IS 'AI평가 고유 번호';
COMMENT ON COLUMN PRODUCT_EVALUATION.ID IS '가이드 상품 고유 번호';
COMMENT ON COLUMN PRODUCT_EVALUATION.CREATED_AT IS '평가 날짜';
COMMENT ON COLUMN PRODUCT_EVALUATION.SCORE IS '점수';
COMMENT ON COLUMN PRODUCT_EVALUATION.CONTENT IS '점수에 대한 내용';
COMMENT ON TABLE RECEIVE_PAYMENT IS '결제 영수증';
COMMENT ON COLUMN RECEIVE_PAYMENT.ID IS '토스에서 받은 결제 고유 번호';
COMMENT ON COLUMN RECEIVE_PAYMENT.ID IS '토스에서 받은 결제 고유 번호';
COMMENT ON COLUMN RECEIVE_PAYMENT.PRICE IS '결제 금액';
COMMENT ON COLUMN RECEIVE_PAYMENT.PAY_METHOD IS '결제 수단';
COMMENT ON COLUMN RECEIVE_PAYMENT.CREATED_AT IS '결제 시간';
COMMENT ON COLUMN RECEIVE_PAYMENT.ISACTIVE IS '결제 성공 유무 : 1 - TRUE
0- FALSE

';
COMMENT ON TABLE REPORT IS '신고';
COMMENT ON COLUMN REPORT.ID IS '상품 고유 번호/신고 대상자';
COMMENT ON COLUMN REPORT.ID IS '회원 고유 번호/신고자 : 회원 고유 ID';
COMMENT ON COLUMN REPORT.ETC IS '기타';
COMMENT ON COLUMN REPORT.CREATED_AT IS '리뷰 날짜';
COMMENT ON COLUMN REPORT.ISACTIVE IS '활성화도 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REPORT.LIST1 IS '평가항목 LIST : 회사 내규에 따름
1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REPORT.LIST2 IS '평가항목 2 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REPORT.LIST3 IS '리스트 3 : 1 - TRUE
0- FALSE

';
COMMENT ON TABLE REVIEW IS '리뷰';
COMMENT ON COLUMN REVIEW.ID IS '상품 고유 번호/신고 대상자';
COMMENT ON COLUMN REVIEW.ID IS '회원 고유 번호/신고자 : 회원 고유 ID';
COMMENT ON COLUMN REVIEW.ID IS '가이드 상품 고유 번호';
COMMENT ON COLUMN REVIEW.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN REVIEW.LIST1 IS '평가항목 LIST : 회사 내규에 따름
1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REVIEW.LIST2 IS '평가항목 2 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REVIEW.LIST3 IS '리스트 3 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REVIEW.ETC IS '기타';
COMMENT ON COLUMN REVIEW.CREATED_AT IS '리뷰 날짜';
COMMENT ON COLUMN REVIEW.ISACTIVE IS '활성화도 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REVIEW.UPDATED_AT IS '수정 날짜';
COMMENT ON COLUMN REVIEW.ISUPDATE IS '수정 유무 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN REVIEW.DELETED_AT IS '삭제 날짜';
COMMENT ON COLUMN REVIEW.ISDELETE IS '삭제 유무 : 1 - TRUE
0- FALSE

';
COMMENT ON TABLE SOCIAL_USER IS '소셜 유저 테이블';
COMMENT ON COLUMN SOCIAL_USER.ID IS '회원 고유 번호 : 회원 고유 ID';
COMMENT ON COLUMN SOCIAL_USER.KAKAO IS '카카오 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN SOCIAL_USER.NAVER IS '네이버 : 1 - TRUE
0- FALSE

';
COMMENT ON COLUMN SOCIAL_USER.GOOGLE IS '구글 : 1 - TRUE
0- FALSE

';
COMMENT ON TABLE TRIP_DAYS IS '여행 일수';
COMMENT ON COLUMN TRIP_DAYS.ID IS '날짜 고유번호';
COMMENT ON COLUMN TRIP_DAYS.ID IS '가이드 상품 고유 번호';
COMMENT ON COLUMN TRIP_DAYS.DAY IS '날짜 : 몇번째 날인지';
COMMENT ON COLUMN TRIP_DAYS.ISUPDATE IS '수정 여부 : 1은 TRUE
0은 FALSE';
COMMENT ON COLUMN TRIP_DAYS.UPDATED_AT IS '수정 날짜';
COMMENT ON COLUMN TRIP_DAYS.ISCREATE IS '생성 여부';
COMMENT ON COLUMN TRIP_DAYS.CREATED_AT IS '생성 날짜';



